name: Code Coverage

on:
  push:
    branches: [main]
  pull_request:

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Deno 2.4.2
        uses: denoland/setup-deno@v1
        with:
          deno-version: 2.4.2

      - name: Run tests with coverage
        run: deno test --coverage=coverage

      - name: Generate LCOV report
        run: deno coverage coverage --lcov > coverage.lcov

      - name: Upload to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: coverage.lcov
#          token: ${{ secrets.CODECOV_TOKEN }}  # Optional if your repo is public
